
-- the 3 types stored as enums.
CREATE TYPE fuel_types AS ENUM ( 'gasoline', 'mild hybrid', 'pure electric');


-- table scheme for vehicles.
BEGIN;
DROP TABLE IF EXISTS vehicles;
CREATE TABLE vehicles (
  license_plate VARCHAR(8) PRIMARY KEY UNIQUE NOT NULL,
  capacity INT NOT NULL,
  range FLOAT NOT NULL,
  fuel fuel_types,
  brand VARCHAR(255),
  model VARCHAR(255)
);
COMMIT;


-- dummy values generated by CHATGPT

INSERT INTO vehicles (license_plate, capacity, range, fuel, brand, model) VALUES
('ABC1234', 5, 450.0, 'gasoline', 'Toyota', 'Corolla'),
('XYZ5678', 4, 520.5, 'mild hybrid', 'Honda', 'Insight'),
('ELEC001', 5, 350.0, 'pure electric', 'Tesla', 'Model 3'),
('HYB1234', 7, 600.0, 'mild hybrid', 'Ford', 'Escape Hybrid'),
('GAS9999', 2, 400.0, 'gasoline', 'BMW', 'X1'),
('ELEC002', 4, 300.0, 'pure electric', 'Nissan', 'Leaf'),
('GAS4321', 5, 480.0, 'gasoline', 'Volkswagen', 'Golf'),
('HYB5678', 5, 550.0, 'mild hybrid', 'Hyundai', 'Ioniq'),
('ELEC003', 5, 370.0, 'pure electric', 'Chevrolet', 'Bolt EV'),
('GAS8765', 4, 460.0, 'gasoline', 'Mazda', 'CX-5'),
('HYB2345', 6, 590.0, 'mild hybrid', 'Kia', 'Niro'),
('ELEC004', 5, 330.0, 'pure electric', 'Audi', 'e-tron'),
('GAS1122', 5, 420.0, 'gasoline', 'Subaru', 'Outback'),
('HYB3456', 7, 610.0, 'mild hybrid', 'Toyota', 'RAV4 Hybrid'),
('ELEC005', 4, 340.0, 'pure electric', 'BMW', 'i3'),
('GAS9988', 5, 470.0, 'gasoline', 'Mercedes-Benz', 'C-Class'),
('HYB7890', 5, 560.0, 'mild hybrid', 'Lexus', 'UX 250h'),
('ELEC006', 5, 360.0, 'pure electric', 'Volkswagen', 'ID.4'),
('GAS2233', 4, 430.0, 'gasoline', 'Honda', 'Civic'),
('HYB4567', 5, 580.0, 'mild hybrid', 'Ford', 'Fusion Hybrid'),
('ELEC007', 5, 390.0, 'pure electric', 'Jaguar', 'I-Pace'),
('GAS3344', 2, 410.0, 'gasoline', 'Mini', 'Cooper'),
('HYB6789', 5, 570.0, 'mild hybrid', 'Toyota', 'Highlander Hybrid'),
('ELEC008', 5, 355.0, 'pure electric', 'Polestar', '2'),
('GAS4455', 5, 440.0, 'gasoline', 'Chevrolet', 'Malibu');